name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: node run-tests.js
    
    - name: Install coverage tools
      run: npm install -g c8
    
    - name: Generate coverage report
      run: c8 --reporter=text --reporter=json-summary --reporter=lcov node run-tests.js
    
    - name: Check coverage threshold
      run: |
        if [ -f ./coverage/coverage-summary.json ]; then
          COVERAGE=$(cat ./coverage/coverage-summary.json | jq -r '.total.lines.pct // 0')
          echo "Code coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Error: Code coverage is below 80%"
            exit 1
          fi
        else
          echo "Warning: Coverage report not found. Skipping coverage check."
        fi
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-report
        path: coverage/
